### ISSUE TITLE
Thanks!!

### ISSUE THREAD

**Issue by zicklag** [evanwinter/sveltekit-page-transitions#3]
Hey there! I just wanted to shout out a quick thanks for this example! It was exactly what I was looking for for my app.

A :star: didn't seem good enough, and I'd have opened a discussion if they were enabled, but an issue will have to do. I hope this ping doesn't bug you. :slightly_smiling_face:

_I'll also close this 'cause it's not an issue._

**Comment by evanwinter** [comment]
Thanks for the feedback, glad it could help!
